export const charFade = (state) => state.game.charFade
export const charFadeIndex = (state) => state.game.charFadeIndex
export const game = (state) => state.game
export const hearts = (state) => state.game.hearts
export const heartsIndex = (state) => state.game.heartsIndex
export const highscores = (state) => state.game.highscores
export const highscoresIndex = (state) => state.game.highscoresIndex
export const numGuesses = (state) => state.game.numGuesses
export const score = (state) => state.game.score
export const status = (state) => state.game.status
export const word = (state) => state.game.word
export const wordGuessed = (state) => state.game.wordGuessed
export const wordGuessedIndex = (state) => state.game.wordGuessedIndex
export const wordLength = (state) => state.game.word.length
